name       : fluxbox
version    : 1.3.7
release    : 3
source     :
    - http://sourceforge.net/projects/fluxbox/files/fluxbox/1.3.7/fluxbox-1.3.7.tar.xz : fc8c75fe94c54ed5a5dd3fd4a752109f8949d6df67a48e5b11a261403c382ec0
license    : MIT
component  : desktop.wm
summary    : Lightweight X11 Window Manager
description: |
    Fluxbox is a windowmanager for X that was based on the Blackbox 0.61.1 code. It is very light on resources and easy to handle but yet full of features to make an easy, and extremely fast, desktop experience. It is built using C++ and licensed under the MIT-License.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(imlib2)
    - pkgconfig(xft)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(xrender)
    - pkgconfig(xpm)
    - pkgconfig(xinerama)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(fribidi)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $pkgfiles/fluxbox.desktop $installdir/usr/share/xsessions/fluxbox.desktop
